### ISSUE TITLE
Improve instructions

### ISSUE THREAD

**Issue by suchow** [thomasmorgan/motion-game#2]
"The canvas below shows you what you will see, use the buttons to see the true motion of the dot, as well as a partial section of the dot and a stuttery version."

to 

"The canvas below shows you what you will see. Use the buttons to see the true motion of the dot, as well as a partial section of the dot's motion, and a version where the dot stutters."

**Comment by suchow** [comment]
It's also not clear that "stuttery" matches up with "previous participant" except that it's the third button. Would be good to link the language there in some way.

**Comment by suchow** [comment]
Lastly, it would be good to be explicit about what you mean by "stutter". It's not that the motion is jerky, but that *replay* of the motion is jerky. Maybe there's a way to attribute the stutter directly to the display / playback mechanism as opposed to the dot.

**Comment by suchow** [comment]
"You are taking part in this experiment as part of a long chain of participants..."

to

"You are taking part in this experiment as part of a long chain of participants,..."  (comma)

**Comment by suchow** [comment]
"as well as a stuttery version of the previous participant" 

to 

"as well as a stuttery version of the previous's participants recreation"

**Comment by thomasmorgan** [comment]
thanks
