### ISSUE TITLE
Initial position unclear

### ISSUE THREAD

**Issue by suchow** [thomasmorgan/motion-game#3]
During playback, my trial began with a black screen and only later did I see the dot moving, so I don't know what the starting position of the dot is. This may be intentional, but as a participant it isn't totally clear whether my recreation should start at the first part I saw or where I think the dot started.

**Comment by thomasmorgan** [comment]
Yes, I have changed the instructions to clarify. I though about ensuring that all participants see the starting point of the dot, but this will reduce the extent to which different participants see different sections of the dot movement so I will not do it for now.
