### ISSUE TITLE
Total length of recreation time is unclear

### ISSUE THREAD

**Issue by suchow** [thomasmorgan/motion-game#4]
I click somewhere on the screen and the dot appears. I start moving it and reproduce the pattern. But then I'm done and ready to stop, but it's not clear whether I should click and then can just move my cursor away, or (what I believe is actually happening) that there's an unseen timer that automatically ends the trial and makes the dot go away and not controlled by my cursor.

bootstrap has loading bars — what if we had a loading bar or something that filled up as the animation went along? maybe an instruction is enough.

**Comment by thomasmorgan** [comment]
yes, I will make clear that the motions are all exactly 5s. I had also thought about the loading bar, I will add that if participants get confused.
